import bottle from '../assets/bottle.svg'

const data = [
  {
    img: bottle,
    title1: "Gordon's Gin",
    title2: "Premium Pink",
    Price: "Rp.299.000",
    size : "700ml",
    company: "Australia Wine",
  },
  {
    img: bottle,
    title1: "Gordon's Gin",
    title2: "Premium Pink",
    Price: "Rp.299.000",
    size : "700ml",
    company: "Australia Wine",
  },
  {
    img: bottle,
    title1: "Gordon's Gin",
    title2: "Premium Pink",
    Price: "Rp.299.000",
    size : "700ml",
    company: "Australia Wine",
  },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.000",
//     size : "700ml",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     size : "700ml",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     size : "700ml",
//     company: "Australia Wine",
//   },

//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     size : "700ml",
//     company: "Australia Wine",
//   },

//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     size : "700ml",
//     company: "Australia Wine",
//   },

//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     size : "700ml",
//     company: "Australia Wine",
//   },

//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.000",
//     size : "700ml",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.000",
//     size : "700ml",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.000",
//     size : "700ml",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.000",
//     size : "700ml",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     company: "Australia Wine",
//   },

//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     company: "Australia Wine",
//   },
//   {
//     img: bottle,
//     title1: "Gordon's Gin",
//     title2: "Premium Pink",
//     Price: "Rp.299.00",
//     company: "Australia Wine",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
//     title: "Vans Unisex Low-Top",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "100",
//     company: "Vans",
//     color: "blue",
//     category: "sandals",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
//     title: "Classic Bandana Sneakers",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "50",
//     company: "Nike",
//     color: "black",
//     category: "sandals",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
//     title: "Chunky High Heel",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "50",
//     company: "Vans",
//     color: "black",
//     category: "heels",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
//     title: "Slip On Stiletto High Heel",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "100",
//     company: "puma",
//     color: "black",
//     category: "heels",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
//     title: "DREAM PAIRS Court Shoes",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "150",
//     company: "Nike",
//     color: "red",
//     category: "heels",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
//     title: "Nike Air Vapormax Plus",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "200",
//     company: "Nike",
//     color: "red",
//     category: "sneakers",
//   },

//   {
//     img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
//     title: "Low Mid Block Heels",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "200",
//     company: "Nike",
//     color: "black",
//     category: "heels",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
//     title: "Chunky High Heel",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "50",
//     company: "Adidas",
//     color: "black",
//     category: "heels",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
//     title: "Amore Fashion Stilettos",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "150",
//     company: "Adidas",
//     color: "white",
//     category: "heels",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
//     title: "Bridal Sandals Glitter",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "50",
//     company: "Adidas",
//     color: "black",
//     category: "heels",
//   },
//   {
//     img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
//     title: "Wedding Prom Bridal",
//     star: <AiFillStar className="rating-star" />,
//     reviews: "(123 reviews)",
//     prevPrice: "$140,00",
//     newPrice: "50",
//     company: "Adidas",
//     color: "black",
//     category: "flats",
//   },
];

export default data;
